# Generated by Django 6.0.4 on 2026-04-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='target_skills',
            field=models.TextField(blank=True),
        ),
    ]
